name: "CI"

env:
  FOUNDRY_PROFILE: "ci"

on:
  [workflow_dispatch]

  
  #pull_request:
  #  branches:
  #    - "main"
  #push:
  #  branches:
  #    - "main"

jobs:
  get_proxy_names:
    name: Get contract names
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix with all contract names from the proxy directory 
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(ls contracts/proxies | sed 's/Proxy.sol//' | jq -R -s -c 'split("\n") | map(select(length > 0))') )"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  check_storage_layout:
    needs: get_proxy_names
    name: Check storage layout
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contract: ${{ fromJson(needs.get_proxy_names.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Check storage layout
        uses: Rubilmax/foundry-storage-check@v3.2.1
        with:
          contract: ${{ matrix.contract }}.sol:${{ matrix.contract }}
          workingDirectory: contracts/
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "onbjerg/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Lint the contracts"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Run the tests"
        run: "forge test"

      - name: "Build the contracts"
        run: |
          forge --version
          forge build --sizes

      - name: "Add test summary"
        run: |
          echo "## Tests" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
